import type { Metadata } from 'next';
import { AppProviders } from '../appProviders';
import './globals.scss';
import { Header } from '@/widgets/header/components/Header';
import { Footer } from '@/widgets/footer/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body>
        <Header />
        <main className="content">
          <AppProviders>{children}</AppProviders>
        </main>
        <Footer />
      </body>
    </html>
  );
}
